type ChartRequest {
  run_id: String @index(unique: true) @immutable
  chart: String
  data: String
  path: String
  path_original: String
  file: String
  x: String
  y: [String]
  line: [String]
  series: String
  size: String
  value: String
  agg: String
  sort: String
  stack: String
  horizontal: Boolean
  bins: String
  title: String
  subtitle: String
  x_label: String
  y_label: String
  y2_label: String
  x_scale: String
  y_scale: String
  y2_scale: String
  format: String
  x_format: String
  y_format: String
  y2_format: String
  legend: String
  theme: String
  colors: [String]
  line_axis: String
  width: Int
  height: Int
  scale: Float
  x_min: Float
  x_max: Float
  y_min: Float
  y_max: Float
  center: Float
  output: String
  save: String
}
